// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dkjjsljmwzskfmyhddby.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRrampzbGptd3pza2ZteWhkZGJ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYyMDQxOTMsImV4cCI6MjA2MTc4MDE5M30.JzLoDqLMa_2ZMWgk-srCo2uPQQVYYgsyT871qwNTiTE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);